---
services:
  netbird:
    image: netbirdio/netbird:latest
    container_name: netbird_radarr
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - NB_SETUP_KEY=${NB_SETUP_KEY_RADARR}
      - NB_HOSTNAME=radarr
    volumes:
      - ./config/config_netbird_radarr/etc:/etc/netbird
      - ./config/config_netbird_radarr/var:/var/lib/netbird
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:netbird
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/config_radarr/data:/config
      - ./movies:/movies
      - ./downloads:/downloads
    depends_on:
      - netbird
    restart: unless-stopped

  caddy:
    image: caddy:alpine
    container_name: caddy_radarr
    network_mode: service:netbird
    volumes:
      - ./caddy/Caddyfile.radarr:/etc/caddy/Caddyfile:ro
      - ./config/config_caddy_radarr/data:/data
      - ./config/config_caddy_radarr/config:/config
    depends_on:
      - netbird
      - radarr
    restart: unless-stopped
